# -*- coding: utf-8 -*-
"""BraTS2020_Training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HA2Abdg5vdoDwSEQCKY9gR76ilXDlF9g

> Connects to Google Drive and verifies we can see the data.
"""

from google.colab import drive
import os
import sys

# 1. Mount Drive (Force remount to fix any stale connections)
drive.mount('/content/drive', force_remount=True)

# 2. Verify Data Access
# We use the path you confirmed earlier
RAW_DATA_PATH = "/content/drive/MyDrive/MICCAI_BraTS2020_TrainingData"
SAVE_PATH = "/content/drive/MyDrive/BraTS2020_Preprocessed_128"

if os.path.exists(RAW_DATA_PATH):
    print(f"✅ SUCCESS: Raw data found at {RAW_DATA_PATH}")
else:
    print(f"❌ WARNING: Could not find data at {RAW_DATA_PATH}")
    print("   Please verify the folder name in your Google Drive.")

"""Finds the raw NIfTI files, normalizes them, fixes the labels, and saves them as fast-loading 4-channel .npy files."""

import os
import glob
import numpy as np
import nibabel as nib
from tqdm import tqdm

# === CONFIGURATION ===
# Using the path verified in previous steps
RAW_PATH = "/content/drive/MyDrive/MICCAI_BraTS2020_TrainingData"
PROCESSED_PATH = "/content/drive/MyDrive/BraTS2020_Preprocessed_128"

# === HELPER: Find files robustly ===
def find_file(folder, suffix_list):
    """Finds a file ending with any of the suffixes in the folder."""
    try:
        files = os.listdir(folder)
        for f in files:
            for suffix in suffix_list:
                if f.endswith(suffix):
                    return os.path.join(folder, f)
    except FileNotFoundError:
        return None
    return None

# === 1. IDENTIFY PATIENTS ===
# Look for folders starting with BraTS20_Training
search_pattern = os.path.join(RAW_PATH, "BraTS20_Training_*")
patient_folders = sorted(glob.glob(search_pattern))

valid_patients = []
print(f"🔍 Scanning {len(patient_folders)} folders for complete data...")

for p in patient_folders:
    # We need all 4 modalities + seg
    has_seg = find_file(p, ["seg.nii", "seg.nii.gz"])
    if has_seg:
        valid_patients.append(p)

print(f"✅ Found {len(valid_patients)} valid patients.")

if len(valid_patients) == 0:
    raise ValueError("❌ No valid patient folders found. Check your RAW_PATH.")

# === 2. SETUP OUTPUT DIRS ===
for split in ['train', 'val']:
    os.makedirs(os.path.join(PROCESSED_PATH, split, 'images'), exist_ok=True)
    os.makedirs(os.path.join(PROCESSED_PATH, split, 'masks'), exist_ok=True)

# Split 80% Train, 20% Val
val_count = int(len(valid_patients) * 0.2)
train_patients = valid_patients[val_count:]
val_patients = valid_patients[:val_count]

# === 3. PREPROCESSING FUNCTION ===
def z_score_normalize(image):
    mask = image > 0
    if mask.sum() == 0: return image
    mean = image[mask].mean()
    std = image[mask].std()
    return (image - mean) / (std + 1e-8)

def process_batch(patient_list, split):
    print(f"🚀 Processing {split} set ({len(patient_list)} patients)...")

    for folder in tqdm(patient_list):
        patient_id = os.path.basename(folder)

        # Output filenames
        out_img = os.path.join(PROCESSED_PATH, split, 'images', f"{patient_id}.npy")
        out_mask = os.path.join(PROCESSED_PATH, split, 'masks', f"{patient_id}.npy")

        # Skip if already exists (Resumable preprocessing!)
        if os.path.exists(out_img) and os.path.exists(out_mask):
            continue

        # Find files
        f_t1 = find_file(folder, ["t1.nii", "t1.nii.gz"])
        f_t1ce = find_file(folder, ["t1ce.nii", "t1ce.nii.gz"])
        f_t2 = find_file(folder, ["t2.nii", "t2.nii.gz"])
        f_flair = find_file(folder, ["flair.nii", "flair.nii.gz"])
        f_seg = find_file(folder, ["seg.nii", "seg.nii.gz"])

        if not all([f_t1, f_t1ce, f_t2, f_flair, f_seg]):
            continue # Skip incomplete

        try:
            # Load
            v_t1 = nib.load(f_t1).get_fdata().astype(np.float32)
            v_t1ce = nib.load(f_t1ce).get_fdata().astype(np.float32)
            v_t2 = nib.load(f_t2).get_fdata().astype(np.float32)
            v_flair = nib.load(f_flair).get_fdata().astype(np.float32)
            v_seg = nib.load(f_seg).get_fdata().astype(np.uint8)

            # Fix Labels (4 -> 3)
            v_seg[v_seg == 4] = 3

            # Normalize
            v_t1 = z_score_normalize(v_t1)
            v_t1ce = z_score_normalize(v_t1ce)
            v_t2 = z_score_normalize(v_t2)
            v_flair = z_score_normalize(v_flair)

            # Stack 4 Channels: [FLAIR, T1, T1ce, T2]
            combined = np.stack([v_flair, v_t1, v_t1ce, v_t2], axis=-1)

            # Crop Center 128 (BraTS is 240x240x155)
            # Center X: 120 -> 56:184
            # Center Y: 120 -> 56:184
            # Center Z: 77 -> 13:141
            combined = combined[56:184, 56:184, 13:141, :]
            v_seg = v_seg[56:184, 56:184, 13:141]

            # Save
            np.save(out_img, combined)
            np.save(out_mask, v_seg)

        except Exception as e:
            print(f"Error processing {patient_id}: {e}")

# Run It
if __name__ == "__main__":
    process_batch(train_patients, 'train')
    process_batch(val_patients, 'val')
    print("\n✅ Preprocessing Complete!")

"""Creates the script file that handles the model, dataset, and training loop. Supports resuming and all 9 activations."""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile train.py
# import os
# import time
# import torch
# import torch.nn as nn
# import torch.optim as optim
# import torch.nn.functional as F
# from torch.utils.data import DataLoader, Dataset
# from torch.optim.lr_scheduler import CosineAnnealingLR
# import pandas as pd
# import numpy as np
# from tqdm import tqdm
# import argparse
# import random
# 
# # ==========================================
# # 1. CONFIGURATION
# # ==========================================
# DATA_DIR = "/content/drive/MyDrive/BraTS2020_Preprocessed_128"
# 
# def seed_everything(seed=42):
#     random.seed(seed)
#     np.random.seed(seed)
#     torch.manual_seed(seed)
#     torch.cuda.manual_seed_all(seed)
#     torch.backends.cudnn.deterministic = True
#     torch.backends.cudnn.benchmark = False
# 
# # ==========================================
# # 2. ACTIVATIONS (12 Functions)
# # ==========================================
# class Mish(nn.Module):
#     def forward(self, x): return x * torch.tanh(F.softplus(x))
# 
# class ELiSH(nn.Module):
#     def forward(self, x): return F.elu(x) * torch.sigmoid(x)
# 
# class HardELiSH(nn.Module):
#     def forward(self, x): return F.elu(x) * F.hardsigmoid(x)
# 
# class Logish(nn.Module):
#     def forward(self, x): return x * torch.log(1 + torch.sigmoid(x))
# 
# class Smish(nn.Module):
#     def forward(self, x): return x * torch.tanh(torch.log(1 + torch.sigmoid(x)))
# 
# class TanhExp(nn.Module):
#     def forward(self, x): return x * torch.tanh(torch.exp(torch.clamp(x, max=20)))
# 
# def get_activation(name):
#     name = name.lower()
#     # Baselines
#     if name == 'relu': return nn.ReLU(inplace=True)
#     if name == 'leaky_relu': return nn.LeakyReLU(0.01, inplace=True)
#     if name == 'prelu': return nn.PReLU()
#     if name == 'elu': return nn.ELU(inplace=True)
#     # Modern
#     if name == 'gelu': return nn.GELU()
#     if name == 'swish': return nn.SiLU(inplace=True)
#     if name == 'mish': return Mish()
#     # Novel / Advanced
#     if name == 'elish': return ELiSH()
#     if name == 'hard_elish': return HardELiSH()
#     if name == 'logish': return Logish()
#     if name == 'smish': return Smish()
#     if name == 'tanhexp': return TanhExp()
#     raise ValueError(f"Activation {name} not supported.")
# 
# # ==========================================
# # 3. DATASET
# # ==========================================
# class BraTSDataset(Dataset):
#     def __init__(self, img_dir, mask_dir):
#         self.img_dir = img_dir
#         self.mask_dir = mask_dir
#         self.files = sorted([f for f in os.listdir(img_dir) if f.endswith('.npy')])
# 
#     def __len__(self): return len(self.files)
# 
#     def __getitem__(self, idx):
#         try:
#             img = np.load(os.path.join(self.img_dir, self.files[idx])).astype(np.float32)
#             mask = np.load(os.path.join(self.mask_dir, self.files[idx])).astype(np.longlong)
#             img = torch.from_numpy(img).permute(3, 2, 0, 1) # (C, D, H, W)
#             mask = torch.from_numpy(mask).permute(2, 0, 1)  # (D, H, W)
#             return img, mask
#         except Exception:
#             # Robust fallback for corrupted files
#             return torch.zeros((4, 128, 128, 128)), torch.zeros((128, 128, 128), dtype=torch.long)
# 
# # ==========================================
# # 4. MODEL (Improved 3D U-Net)
# # ==========================================
# class ResidualBlock(nn.Module):
#     def __init__(self, in_c, out_c, act_name):
#         super().__init__()
#         self.conv1 = nn.Conv3d(in_c, out_c, 3, padding=1)
#         self.bn1 = nn.BatchNorm3d(out_c)
#         self.act = get_activation(act_name)
#         self.conv2 = nn.Conv3d(out_c, out_c, 3, padding=1)
#         self.bn2 = nn.BatchNorm3d(out_c)
#         self.skip = nn.Conv3d(in_c, out_c, 1) if in_c != out_c else nn.Identity()
# 
#     def forward(self, x):
#         return self.act(self.bn2(self.conv2(self.act(self.bn1(self.conv1(x))))) + self.skip(x))
# 
# class ImprovedUNet3D(nn.Module):
#     def __init__(self, in_c, out_c, act_name):
#         super().__init__()
#         # Encoder
#         self.enc1 = ResidualBlock(in_c, 32, act_name); self.pool = nn.MaxPool3d(2)
#         self.enc2 = ResidualBlock(32, 64, act_name)
#         self.enc3 = ResidualBlock(64, 128, act_name)
#         self.enc4 = ResidualBlock(128, 256, act_name)
#         self.bottleneck = ResidualBlock(256, 512, act_name)
#         # Decoder
#         self.up4 = nn.ConvTranspose3d(512, 256, 2, 2); self.dec4 = ResidualBlock(512, 256, act_name)
#         self.up3 = nn.ConvTranspose3d(256, 128, 2, 2); self.dec3 = ResidualBlock(256, 128, act_name)
#         self.up2 = nn.ConvTranspose3d(128, 64, 2, 2); self.dec2 = ResidualBlock(128, 64, act_name)
#         self.up1 = nn.ConvTranspose3d(64, 32, 2, 2); self.dec1 = ResidualBlock(64, 32, act_name)
#         self.out = nn.Conv3d(32, out_c, 1)
# 
#     def forward(self, x):
#         e1=self.enc1(x)
#         e2=self.enc2(self.pool(e1))
#         e3=self.enc3(self.pool(e2))
#         e4=self.enc4(self.pool(e3))
#         b = self.bottleneck(self.pool(e4))
# 
#         d4=self.dec4(torch.cat([self.up4(b), e4], 1))
#         d3=self.dec3(torch.cat([self.up3(d4), e3], 1))
#         d2=self.dec2(torch.cat([self.up2(d3), e2], 1))
#         d1=self.dec1(torch.cat([self.up1(d2), e1], 1))
#         return self.out(d1)
# 
# # ==========================================
# # 5. TRAINING ENGINE
# # ==========================================
# if __name__ == "__main__":
#     parser = argparse.ArgumentParser()
#     parser.add_argument('--act', type=str, required=True)
#     parser.add_argument('--name', type=str, required=True)
#     parser.add_argument('--epochs', type=int, default=100)
#     args = parser.parse_args()
# 
#     seed_everything()
#     SAVE_DIR = f"/content/drive/MyDrive/BraTS_Results/{args.name}"
#     os.makedirs(SAVE_DIR, exist_ok=True)
# 
#     device = 'cuda' if torch.cuda.is_available() else 'cpu'
#     print(f"🚀 Started: {args.name} | Act: {args.act}")
# 
#     # Init Components
#     model = ImprovedUNet3D(4, 4, args.act).to(device)
#     optimizer = optim.AdamW(model.parameters(), lr=3e-4)
#     scaler = torch.amp.GradScaler('cuda')
#     ce_loss = nn.CrossEntropyLoss()
#     scheduler = CosineAnnealingLR(optimizer, T_max=args.epochs)
# 
#     # --- RESUME LOGIC (With Fixes) ---
#     ckpt_path = os.path.join(SAVE_DIR, "latest.pth")
#     start_epoch = 0; history = []
# 
#     if os.path.exists(ckpt_path):
#         print("🔄 Resuming from checkpoint...")
#         # FIX 1: weights_only=False for PyTorch 2.6+ compatibility
#         ckpt = torch.load(ckpt_path, map_location=device, weights_only=False)
#         model.load_state_dict(ckpt['model'])
#         optimizer.load_state_dict(ckpt['opt'])
#         start_epoch = ckpt['epoch']
#         history = ckpt.get('history', [])
# 
#         # FIX 2: Restore Scheduler to prevent Loss Spike
#         if 'scheduler' in ckpt:
#             scheduler.load_state_dict(ckpt['scheduler'])
#         else:
#             # Fallback for old checkpoints: fast-forward scheduler
#             print("   (Re-aligning scheduler...)")
#             for _ in range(start_epoch): scheduler.step()
# 
#     # Data Loaders
#     train_dl = DataLoader(BraTSDataset(f"{DATA_DIR}/train/images", f"{DATA_DIR}/train/masks"),
#                           batch_size=2, shuffle=True, num_workers=2, pin_memory=True)
#     val_dl = DataLoader(BraTSDataset(f"{DATA_DIR}/val/images", f"{DATA_DIR}/val/masks"),
#                         batch_size=2, shuffle=False, num_workers=2, pin_memory=True)
# 
#     # --- MAIN LOOP ---
#     for epoch in range(start_epoch, args.epochs):
#         torch.cuda.reset_peak_memory_stats()
#         epoch_start = time.time()
# 
#         # 1. Train
#         model.train()
#         t_loss = 0
#         for x, y in tqdm(train_dl, desc=f"Ep {epoch+1} Train", leave=False):
#             x, y = x.to(device), y.to(device)
#             optimizer.zero_grad()
#             with torch.amp.autocast('cuda'):
#                 pred = model(x)
#                 # Combined Loss (CE + Dice)
#                 p_soft = F.softmax(pred, 1)
#                 y_oh = F.one_hot(y, 4).permute(0,4,1,2,3).float()
#                 inter = (p_soft * y_oh).sum((2,3,4))
#                 union = p_soft.sum((2,3,4)) + y_oh.sum((2,3,4))
#                 dice_loss = 1 - ((2*inter+1e-5)/(union+1e-5)).mean()
#                 loss = ce_loss(pred, y) + dice_loss
# 
#             scaler.scale(loss).backward()
#             scaler.step(optimizer); scaler.update()
#             t_loss += loss.item()
# 
#         train_loss_avg = t_loss / len(train_dl)
# 
#         # 2. Validate
#         model.eval()
#         v_loss = 0
#         dices = np.zeros(4)
#         precisions = np.zeros(4)
#         sensitivities = np.zeros(4)
# 
#         with torch.no_grad():
#             for x, y in tqdm(val_dl, desc=f"Ep {epoch+1} Val", leave=False):
#                 x, y = x.to(device), y.to(device)
#                 with torch.amp.autocast('cuda'):
#                     pred = model(x)
#                     # Val Loss
#                     p_soft = F.softmax(pred, 1)
#                     y_oh = F.one_hot(y, 4).permute(0,4,1,2,3).float()
#                     inter = (p_soft * y_oh).sum((2,3,4))
#                     union = p_soft.sum((2,3,4)) + y_oh.sum((2,3,4))
#                     dice_loss = 1 - ((2*inter+1e-5)/(union+1e-5)).mean()
#                     loss = ce_loss(pred, y) + dice_loss
#                 v_loss += loss.item()
# 
#                 # Val Metrics
#                 p_cls = pred.argmax(1)
#                 for c in range(4):
#                     p = (p_cls==c).float(); t = (y==c).float()
#                     tp = (p * t).sum()
#                     fp = (p * (1-t)).sum()
#                     fn = ((1-p) * t).sum()
# 
#                     dices[c] += ((2*tp + 1e-5)/(2*tp + fp + fn + 1e-5)).item()
#                     precisions[c] += ((tp + 1e-5)/(tp + fp + 1e-5)).item()
#                     sensitivities[c] += ((tp + 1e-5)/(tp + fn + 1e-5)).item()
# 
#         # 3. Stats
#         val_loss_avg = v_loss / len(val_dl)
#         dices /= len(val_dl)
#         precisions /= len(val_dl)
#         sensitivities /= len(val_dl)
# 
#         mean_dice = dices[1:].mean()
#         mean_prec = precisions[1:].mean()
#         mean_sens = sensitivities[1:].mean()
# 
#         duration = time.time() - epoch_start
#         max_mem = torch.cuda.max_memory_allocated() / 1e9 # GB
# 
#         print(f"Ep {epoch+1}: T_Loss={train_loss_avg:.4f} | V_Loss={val_loss_avg:.4f} | Dice={mean_dice:.4f} | Mem={max_mem:.2f}GB")
# 
#         # 4. Save
#         history.append([epoch+1, train_loss_avg, val_loss_avg, mean_dice, *dices, mean_prec, *precisions, mean_sens, *sensitivities, duration, max_mem])
# 
#         # Save Checkpoint (Include Scheduler!)
#         torch.save({
#             'epoch': epoch+1,
#             'model': model.state_dict(),
#             'opt': optimizer.state_dict(),
#             'scheduler': scheduler.state_dict(), # Saving Scheduler State
#             'history': history
#         }, ckpt_path)
# 
#         # Save Best Model
#         if mean_dice >= max([h[3] for h in history]):
#             torch.save(model.state_dict(), os.path.join(SAVE_DIR, "best_model.pth"))
# 
#         # Log CSV
#         cols = ['epoch','train_loss','val_loss','mean_dice',
#                 'dice_bg','dice_necro','dice_edema','dice_enh',
#                 'mean_prec','prec_bg','prec_necro','prec_edema','prec_enh',
#                 'mean_sens','sens_bg','sens_necro','sens_edema','sens_enh',
#                 'time','max_mem_gb']
#         pd.DataFrame(history, columns=cols).to_csv(os.path.join(SAVE_DIR, "log.csv"), index=False)
# 
#         scheduler.step()
# 
#     print("✅ Experiment Complete.")

"""Creates a bash script to run all 9 experiments one after another. If Colab stops, just re-run Cell 5."""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile run_all.sh
# #!/bin/bash
# 
# # Define the full 12-activation study
# experiments=(
#     # Group 1: Baselines
#     "relu Exp1_ReLU"
#     "leaky_relu Exp2_Leaky"
#     "prelu Exp3_PReLU"
#     "elu Exp4_ELU"
# 
#     # Group 2: Modern
#     "gelu Exp5_GELU"
#     "swish Exp6_Swish"
#     "mish Exp7_Mish"
# 
#     # Group 3: Advanced/Novel
#     "elish Exp8_ELiSH"
#     "hard_elish Exp9_HardELiSH"
#     "logish Exp10_Logish"
#     "smish Exp11_Smish"
#     "tanhexp Exp12_TanhExp"
# )
# 
# echo "🚀 LAUNCHING COMPREHENSIVE 12-ACTIVATION STUDY..."
# echo "=================================================="
# 
# for exp in "${experiments[@]}"; do
#     set -- $exp
#     ACT=$1
#     NAME=$2
# 
#     echo "▶️  STARTING: $NAME (Act: $ACT)"
# 
#     # Run Script (Auto-resumes if interrupted)
#     python train.py --act $ACT --name $NAME --epochs 100
# 
#     echo "✅ FINISHED: $NAME"
#     echo "--------------------------------------"
# done
# 
# echo "🎉 ALL EXPERIMENTS COMPLETE!"

"""Runs the sequencer in the background. Close your browser if you want (but enable background execution in settings first)."""

!nohup bash run_all.sh > global_log.txt 2>&1 &
print("🚀 Training launched! Check global_log.txt for progress.")

"""Checks the status of your experiments."""

!tail -n 20 global_log.txt

import time
import os

# The log file your run_all.sh script writes to
log_file = "global_log.txt"

print(f"⏳ Waiting for {log_file} to be created by the training script...")

# 1. Loop until the file actually exists (prevents error if you run this too fast)
while not os.path.exists(log_file):
    time.sleep(2)

print(f"✅ {log_file} found! Streaming output...")
print("----------------------------------------------------------------")
print("NOTE: Do not close this tab. As long as this text moves, Colab is alive.")
print("----------------------------------------------------------------")

# 2. 'tail -f' follows the file forever.
# The constant printing tells Colab: "I am working, do not disconnect me."
!tail -f {log_file}